version: '3'

services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 13306:3306
    volumes:
    - /opt/docker/mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
    - 16379:6379
  chromium:
    image: repigeons/chromium
    container_name: chromium
    restart: always

  core:
    image: njnu-classroom-core
    build:
      context: .
      dockerfile: docker-core.Dockerfile
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active=pro"]
    restart: always
    depends_on:
    - mysql
    - redis
    - chromium
    ports:
    - 18081:8080
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: "curl -sS http://localhost:8080/actuator/health || exit 1"
  explore:
    image: njnu-classroom-explore
    build:
      context: .
      dockerfile: docker-explore.Dockerfile
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active=pro"]
    restart: always
    depends_on:
    - mysql
    - redis
    ports:
    - 18082:8080
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: "curl -sS http://localhost:8080/actuator/health || exit 1"
