version: '3'

services:
  core:
    image: njnu-classroom-core:latest
    build:
      context: .
      dockerfile: docker-core.Dockerfile
  explore:
    image: njnu-classroom-explore:latest
    build:
      context: .
      dockerfile: docker-explore.Dockerfile
