/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.7.20"
    id("cn.repigeons.njnu.classroom.conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-mail:2.7.5")
    implementation("org.springframework:spring-tx:5.3.23")
    implementation("org.mariadb.jdbc:mariadb-java-client:3.0.3")
    implementation("org.mybatis:mybatis:3.5.9")
    implementation("org.mybatis.generator:mybatis-generator-core:1.4.0")
    implementation("org.mybatis.dynamic-sql:mybatis-dynamic-sql:1.3.1")
    implementation("com.github.pagehelper:pagehelper:5.3.2")
    implementation("org.redisson:redisson-spring-boot-starter:3.17.5")
    implementation("com.google.code.gson:gson:2.8.9")
    implementation("io.jsonwebtoken:jjwt:0.9.1")
}
