application:
  server:
    host: "0.0.0.0"
    port: 8001
    log: "/data/logs/server.log"
    service: on

  explore:
    host: "0.0.0.0"
    port: 8002
    log: "/data/logs/explore.log"
    service: on

  notice:
    host: "0.0.0.0"
    port: 8000
    log: "/data/logs/notice.log"
    token: ""
    file: "notice.json"

  spider:
    log: "/data/logs/spider.log"
    account:
      username: ""
      password: ""
      gid: ""
    selenium:
      driver: "chrome"
      list:
        phantomjs:
          executable_path: "phantomjs"
        chrome:
          executable_path: "chromedriver"
        firefox:
          executable_path: "geckodriver"
          firefox_binary: "firefox"

database:
  mysql:
    host: "mysql"
    port: 3306
    user: "root"
    password: ""
    database: ""
  redis:
    host: "redis"
    port: 6379
    db: 0

mail:
  sender:
    host: "smtp.njnu.edu.cn"
    port: 994
    user: "*@njnu.edu.cn"
    password: ""
  receivers:
    - name: "Repigeons"
      addr: "info@repigeons.cn"
