service: on

application:
  server:
    host: "0.0.0.0"
    port: 80
    log: "logs/server.log"

  explore:
    host: "0.0.0.0"
    port: 80
    log: "logs/explore.log"

  notice:
    host: "0.0.0.0"
    port: 80
    log: "logs/notice.log"
    token: ""
    file: "static/notice.json"

  spider:
    log: "logs/spider.log"
    account:
      username: ""
      password: ""
      gid: ""
    selenium:
      driver: "chrome"
      list:
        phantomjs:
          executable_path: "phantomjs"
        chrome:
          executable_path: "chromedriver"
        firefox:
          executable_path: "geckodriver"
          firefox_binary: "firefox"

  mail:
    sender:
      host: "smtp.njnu.edu.cn"
      port: 994
      user: "*@njnu.edu.cn"
      password: ""
    receivers:
      - name: "Repigeons"
        addr: "info@repigeons.cn"


database:
  mysql:
    host: "mysql"
    port: 3306
    user: "root"
    password: ""
    database: ""
  redis:
    host: "redis"
    port: 6379
    db: 0
