/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.7.20"
    kotlin("plugin.spring") version "1.7.20"
    id("org.springframework.boot") version "2.7.5"
    id("io.spring.dependency-management") version "1.1.0"
    id("cn.repigeons.njnu.classroom.conventions")
}

dependencies {
    implementation(project(":portable"))
    implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2")
    implementation("org.mybatis.dynamic-sql:mybatis-dynamic-sql:1.3.1")
    implementation("org.seleniumhq.selenium:selenium-java:4.3.0")
    implementation("com.squareup.okhttp3:okhttp:3.14.9")
    implementation("com.google.code.gson:gson:2.8.9")
    implementation("org.redisson:redisson:3.17.5")
}
