spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/njnu_classroom
    username: njnu_classroom_root
    password: njnu-000
    hikari:
      maximum-pool-size: 100
  mail:
    host: smtp.repigeons.cn
    port: 465
    username: ''
    password: ''
    receivers: ''

jwt:
  secret: ''
  expire: 86400

mp:
  appid: wx42f3e578c5411a23
  secret: ''
