spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/NjnuClassroom
    username: root
    password: root
  mail:
    host: smtp.repigeons.cn
    port: 465
    username: ''
    password: ''
    properties:
      smtp:
        ssl:
          enable: true
    receivers: ''
