version: '3'

services:
  compile:
    image: maven
    container_name: maven
    command: ["mvn", "clean", "kotlin:compile", "package", "-Dmaven.test.skip=true"]
    volumes:
    - /root/.m2:/root/.m2
    - /opt/njnu_classroom/backend:/home
    working_dir: /home
