version: '3'

services:
  compile_spider:
    image: openjdk:18-slim
    container_name: compile_spider
    command: ["./gradlew", "clean", "build", "-p", "spider", "-x", "test", "--parallel"]
    working_dir: /home
    volumes:
    - /root/.m2:/root/.m2
    - /root/.gradle:/root/.gradle
    - /opt/njnu_classroom/NjnuClassroom/backend:/home

  compile_core:
    image: openjdk:18-slim
    container_name: compile_core
    command: ["./gradlew", "clean", "build", "-p", "spider", "-x", "test", "--parallel"]
    working_dir: /home
    volumes:
    - /root/.m2:/root/.m2
    - /root/.gradle:/root/.gradle
    - /opt/njnu_classroom/NjnuClassroom/backend:/home

  compile_explore:
    image: openjdk:18-slim
    container_name: compile_explore
    command: ["./gradlew", "clean", "build", "-p", "spider", "-x", "test", "--parallel"]
    working_dir: /home
    volumes:
    - /root/.m2:/root/.m2
    - /root/.gradle:/root/.gradle
    - /opt/njnu_classroom/NjnuClassroom/backend:/home
