version: '3'

services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 13306:3306
    volumes:
    - /opt/docker/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
    - 16379:6379
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  core:
    image: njnu-classroom-core:latest
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active="]
    restart: always
    depends_on:
    - mysql
    - redis
    ports:
    - 18081:8080
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
  explore:
    image: njnu-classroom-explore:latest
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active="]
    restart: always
    depends_on:
    - mysql
    - redis
    ports:
    - 18082:8080
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
  spider:
    image: njnu-classroom-spider:latest
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active="]
    restart: always
    depends_on:
    - mysql
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
