version: '3'

services:
  redis:
    restart: always
    image: redis:7-alpine
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  spider:
    restart: always
    image: njnu-classroom-spider:production
    build:
      context: /opt/njnu_classroom/NjnuClassroom/backend
      dockerfile: /opt/njnu_classroom/NjnuClassroom/backend/dockerfile/Dockerfile.spider.dockerfile
      cache_from:
      - openjdk:18-slim
      - njnu-classroom-spider:cache
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active=pro"]
    depends_on:
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
  core:
    restart: always
    image: njnu-classroom-core:production
    build:
      context: /opt/njnu_classroom/NjnuClassroom/backend
      dockerfile: /opt/njnu_classroom/NjnuClassroom/backend/dockerfile/Dockerfile.core.dockerfile
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active=pro"]
    depends_on:
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
  explore:
    restart: always
    image: njnu-classroom-explore:production
    build:
      context: /opt/njnu_classroom/NjnuClassroom/backend
      dockerfile: /opt/njnu_classroom/NjnuClassroom/backend/dockerfile/Dockerfile.explore.dockerfile
    command: ["java", "-jar", "/server.jar", "--spring.profiles.active=pro"]
    depends_on:
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    restart: always
    image: njnu-classroom-nginx:production
    build:
      context: /opt/njnu_classroom/NjnuClassroom/backend
      dockerfile: /opt/njnu_classroom/NjnuClassroom/backend/dockerfile/Dockerfile.nginx.dockerfile
    depends_on:
    - spider
    - core
    - explore
    environment:
      TZ: Asia/Shanghai
    ports:
    - 10080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443"]
