/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    `application`
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.7.20")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.5")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.7.20")
}

group = "cn.repigeons.njnu.classroom"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_18

application.mainClass.set("cn.repigeons.njnu.classroom.MainKt")
